services:
  postgres:
    image: postgres:14.3
    tmpfs:
      - /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --dbname $$POSTGRES_DB --username $$POSTGRES_USER"]
      interval: 1s
      timeout: 5s
      start_period: 5s
      retries: 3
    environment: &postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: docker
  app:
    build: .
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PORT: 8000
      GIN_MODE: debug
      CGO_ENABLED: 0
      <<: *postgres
