name: Vet
on: push
jobs:
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19.0"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - run: go vet ./...
